package ss.week3.pw;

/**
 * Password class to set/test/change a password.
 * @author Tycho
 * @version $1.0
 */
public class Password {
	
	public static final String INITIAL = "banaan";
	private String pass;
	private Checker checker;
	private String factoryPassword;
	
	// ----------- Constructor: ------------
	
	/**
	 * Creates a <code>Password</code> with the given checker and
	 * 						a password generated by the checker.
	 */
	public Password(Checker c) {
		checker = c;
		factoryPassword = checker.generatePassword();
		pass = factoryPassword;
	}
	
	/**
	 * Creates a <code>Password</code> with a <code>BasicChecker</code>
	 * 			and a password generated by the <code>BasicChecker</code>.
	 */
	public Password() {
		this(new BasicChecker());
	}
	
	// ----------- Queries: ----------------
	
	/**
	 * Gives the factory password, the value a <code>Password</code> is initialised with. 
	 * @return the factory password
	 */
	public String getFactoryPassword() {
		return factoryPassword;
	}
	
	// ----------- Commands: ---------------
	
	/**
	 * Tests if a given String is an acceptable password.
	 * Not acceptable is a String with less than 6 characters or a String that contains a space.
	 * @param suggestion is the String to be checked
	 * @return true if it's acceptable
	 */
	/*@ pure */	public static boolean acceptable(String suggestion) {
		return suggestion.length() >= 6 && !suggestion.contains(" ");
	}
	
	/**
	 * Changes the password to a new password.
	 * @param oldpass the current password
	 * @param newpass the new password
	 * @return true if oldpass is equal to current pass and newpass is acceptable
	 */
	public boolean setWord(String oldpass, String newpass) {
		boolean result = false;
		if (testWord(oldpass)) {
			if (acceptable(newpass)) {
				pass = newpass;
				result = true;
			}
		}
		return result;
	}

	/**
	 * Tests if a given word is equal to the current password.
	 * @param test is the word to be tested
	 * @return true if test is equal to the current password
	 */
	/*@ pure */	public boolean testWord(String test) {
		return pass.equals(test);
	}
}
